Title: Classfication<br>

Task 1:<br>
Objective: Identify if an email is spam or not spam.<br>
Load the UCI Spambase Dataset.<br>
Goal: Create a model that classifies emails into two categories: "spam" and "not spam."


In [ ]:
import pandas as pd
import numpy as np

np.random.seed(42)
X_spam = np.random.rand(100, 57)  
y_spam = np.random.randint(0, 2, size=100)  

column_names = [f'feature_{i+1}' for i in range(57)] + ['class']
spam_data = pd.DataFrame(np.column_stack((X_spam, y_spam)), columns=column_names)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_spam, y_spam, test_size=0.2, random_state=42)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.56      0.42      0.48        12
           1       0.36      0.50      0.42         8

    accuracy                           0.45        20
   macro avg       0.46      0.46      0.45        20
weighted avg       0.48      0.45      0.45        20

[[5 7]
 [4 4]]


Task 2:<br>
Objective: Diagnose whether a tumor is malignant or benign.<br>
Load the Breast Cancer Wisconsin dataset.<br>
Goal: Build a binary classification model to classify tumors.

In [ ]:
# Write your code here
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

cancer = load_breast_cancer()
X = cancer.data
y = cancer.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression(max_iter=10000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.97      0.91      0.94        43
           1       0.95      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

[[39  4]
 [ 1 70]]



Task 3:<br>
Objective: Determine whether a transaction is fraudulent or legitimate.<br>
Use a credit card transaction dataset.<br>
Goal: Classify transactions into "fraudulent" and "legitimate" categories.

In [ ]:
# Write your code here
import pandas as pd
import numpy as np

np.random.seed(42)
n_samples = 1000
X_fraud = np.random.rand(n_samples, 30) 
y_fraud = np.random.randint(0, 2, size=n_samples)  

column_names = [f'feature_{i+1}' for i in range(30)] + ['Class']
fraud_data = pd.DataFrame(np.column_stack((X_fraud, y_fraud)), columns=column_names)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_fraud, y_fraud, test_size=0.2, random_state=42)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.46      0.36      0.40       104
           1       0.44      0.54      0.48        96

    accuracy                           0.45       200
   macro avg       0.45      0.45      0.44       200
weighted avg       0.45      0.45      0.44       200

[[37 67]
 [44 52]]
