Title: Popular Classification Algorithms


Decision Trees


Task 1: Predict the loan default risk based on borrower characteristics.

In [ ]:
# Write your code here
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

data = {
    'Income': [45000, 60000, 35000, 80000, 40000, 75000, 50000, 85000, 30000, 95000],
    'Age': [25, 30, 23, 40, 35, 50, 45, 55, 28, 60],
    'Credit Score': [650, 700, 600, 750, 650, 800, 700, 750, 620, 820],
    'Loan Default': [0, 0, 1, 0, 1, 0, 0, 0, 1, 0]  # 0 = No, 1 = Yes
}

df = pd.DataFrame(data)

X = df[['Income', 'Age', 'Credit Score']]
y = df['Loan Default']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

dtree = DecisionTreeClassifier(random_state=42)
dtree.fit(X_train, y_train)

y_pred = dtree.predict(X_test)

print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         1

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

Confusion Matrix:
 [[2 0]
 [0 1]]


Task 2: Determine if a patient should be tested for a disease based on symptoms.

In [ ]:
# Write your code here
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

data = {
    'Fever': [1, 0, 1, 0, 1, 0, 1, 0, 1, 1], 
    'Cough': [1, 0, 1, 0, 1, 0, 1, 0, 1, 1],
    'Fatigue': [1, 0, 1, 0, 1, 0, 1, 0, 1, 1],
    'Test Disease': [1, 0, 1, 0, 1, 0, 1, 0, 1, 1]  
}

df = pd.DataFrame(data)

X = df[['Fever', 'Cough', 'Fatigue']]
y = df['Test Disease']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

dtree = DecisionTreeClassifier(random_state=42)
dtree.fit(X_train, y_train)

y_pred = dtree.predict(X_test)

print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         1

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

Confusion Matrix:
 [[2 0]
 [0 1]]


Task 3: Classify types of animals based on features like size, habitat, and diet.

In [ ]:
# Write your code here
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

data = {
    'Size': ['Large', 'Medium', 'Small', 'Large', 'Medium', 'Small', 'Large', 'Small', 'Medium', 'Large'],
    'Habitat': ['Forest', 'Desert', 'Forest', 'Jungle', 'Desert', 'Ocean', 'Jungle', 'Ocean', 'Forest', 'Jungle'],
    'Diet': ['Carnivore', 'Herbivore', 'Carnivore', 'Omnivore', 'Herbivore', 'Carnivore', 'Omnivore', 'Herbivore', 'Omnivore', 'Carnivore'],
    'Animal Type': ['Tiger', 'Camel', 'Rabbit', 'Bear', 'Elephant', 'Shark', 'Monkey', 'Fish', 'Wolf', 'Lion']
}

df = pd.DataFrame(data)
df = pd.get_dummies(df, columns=['Size', 'Habitat', 'Diet'])

X = df.drop('Animal Type', axis=1)
y = df['Animal Type']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

dtree = DecisionTreeClassifier(random_state=42)
dtree.fit(X_train, y_train)

y_pred = dtree.predict(X_test)

print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Classification Report:
               precision    recall  f1-score   support

        Bear       0.00      0.00      0.00       0.0
       Camel       0.00      0.00      0.00       1.0
    Elephant       0.00      0.00      0.00       0.0
      Rabbit       0.00      0.00      0.00       0.0
       Shark       0.00      0.00      0.00       1.0
        Wolf       0.00      0.00      0.00       1.0

    accuracy                           0.00       3.0
   macro avg       0.00      0.00      0.00       3.0
weighted avg       0.00      0.00      0.00       3.0

Confusion Matrix:
 [[0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [1 0 0 0 0 0]]


/home/vscode/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/vscode/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/vscode/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/vscode/.local/lib/python