Title: Popular Classification Algorithms


K Nearst Neighbors (KNN)

Task 1: Classify fruits based on weight and color.

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

data = {
    'Weight': [120, 130, 140, 150, 110, 200, 210, 190, 180, 170, 300, 310, 320, 305, 295],
    'ColorScore': [0.9, 0.85, 0.88, 0.87, 0.86, 0.5, 0.48, 0.52, 0.55, 0.53, 0.3, 0.35, 0.33, 0.32, 0.31],
    'Fruit': ['Apple'] * 5 + ['Banana'] * 5 + ['Watermelon'] * 5
}
df = pd.DataFrame(data)
X = df[['Weight', 'ColorScore']]
y = df['Fruit']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0, stratify=y)

model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Classification Report:\n", classification_report(y_test, y_pred, zero_division=0))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Classification Report:
               precision    recall  f1-score   support

       Apple       1.00      1.00      1.00         2
      Banana       1.00      1.00      1.00         2
  Watermelon       1.00      1.00      1.00         1

    accuracy                           1.00         5
   macro avg       1.00      1.00      1.00         5
weighted avg       1.00      1.00      1.00         5

Confusion Matrix:
 [[2 0 0]
 [0 2 0]
 [0 0 1]]


Task 2: Predict customer clothing size based on height and weight.

In [5]:
# Write your code here
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

data = {
    'Height': [160, 170, 175, 180, 165, 155, 190, 185, 167, 172],
    'Weight': [55, 65, 70, 80, 60, 50, 90, 85, 62, 68],
    'Size': ['S', 'M', 'M', 'L', 'S', 'S', 'L', 'L', 'M', 'M']
}

df = pd.DataFrame(data)

X = df[['Height', 'Weight']]
y = df['Size']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Classification Report:
               precision    recall  f1-score   support

           M       1.00      0.50      0.67         2
           S       0.50      1.00      0.67         1

    accuracy                           0.67         3
   macro avg       0.75      0.75      0.67         3
weighted avg       0.83      0.67      0.67         3

Confusion Matrix:
 [[1 1]
 [0 1]]


Task 3: Determine optimal movie recommendation based on viewer preferences.

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

data = {
    'Preference': [7, 6, 5, 8, 6, 4, 5, 3, 6, 7, 9, 2],
    'Genre': ['Action', 'Action', 'Action', 'Action', 'Comedy', 'Comedy', 'Comedy', 'Drama', 'Drama', 'Drama', 'Drama', 'Drama']
}
df = pd.DataFrame(data)

X = df[['Preference']]
y = df['Genre']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0, stratify=y)

model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Classification Report:\n", classification_report(y_test, y_pred, zero_division=0))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Classification Report:
               precision    recall  f1-score   support

      Action       0.33      1.00      0.50         1
      Comedy       0.00      0.00      0.00         1
       Drama       0.00      0.00      0.00         1

    accuracy                           0.33         3
   macro avg       0.11      0.33      0.17         3
weighted avg       0.11      0.33      0.17         3

Confusion Matrix:
 [[1 0 0]
 [1 0 0]
 [1 0 0]]
